# App name
spring.application.name=StockSentinel

# H2 Database (Development)
spring.datasource.url=jdbc:h2:file:./data/stocksentineldb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=stocksentinel_super_secret_key_2024_must_be_long_enough
jwt.expiration=86400000

# Finnhub API
finnhub.api.key=d7ekefhr01qi33g6kgu0d7ekefhr01qi33g6kgug

# Alpha Vantage API
alphavantage.api.key=D8W4XATZ1HRM2QB2

# Email Configuration (update with real credentials before demo)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vinisuyal2205@gmail.com
spring.mail.password=romi jbyy dkuh ktwa
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Logging
logging.level.com.stocksentinel=DEBUG
logging.level.org.springframework.security=INFO
